// Package traefik registers antiloop's per-process metrics endpoint
// with a host-level Traefik instance via its file provider, instead of
// antiloop binding to a manually-assigned, per-centre static port.
//
// METRICS_ADDR defaults to :0 (any free port the OS hands out) rather
// than a fixed per-centre value tracked and kept unique by hand
// somewhere else. This package writes a small Traefik dynamic config
// file recording whichever port got assigned; Traefik's file provider
// picks it up automatically (assuming its static config already
// watches this directory), so no manual port registry is needed and no
// collisions are possible.
//
// Routing is path-based: one shared Traefik entrypoint/hostname,
// routed by path prefix /<centre_id>/, rather than a subdomain per
// centre. Traefik forwards the FULL path including the centre_id
// prefix, but antiloop's own metricsMux registers unprefixed routes
// (/metrics, /health, /primary — see cmd/antiloop/main.go), so the
// generated router also carries a stripPrefix middleware that strips
// /<centre_id> back off before the request reaches antiloop. The
// prefix is exactly /<centre_id> (not /metrics/<centre_id>) so that
// /<centre_id>/metrics, /<centre_id>/health, and /<centre_id>/primary
// all strip down to exactly the paths antiloop's mux registers.
package traefik

import (
	"fmt"
	"os"
	"path/filepath"
)

// dynamicConfigTemplate is Traefik's file-provider YAML shape: one
// router (path-matched, stripping the centre_id prefix), one service
// (a single backend — antiloop's own HTTP server, which serves
// /metrics, /health, and /primary, not just metrics), one middleware.
// Names are all keyed by centre_id alone, so multiple centres' files
// never collide inside Traefik's merged dynamic configuration (every
// *.yml in the watched directory gets merged into one namespace) —
// router, middleware, and service names live in separate Traefik
// namespaces (http.routers.X vs http.middlewares.X vs
// http.services.X), so reusing the bare centre_id for both the router
// and the service isn't a collision.
//
// Two things are essential for the router to actually be reachable,
// not just build without error:
//
//  1. entryPoints must always be set explicitly. A router with no
//     entryPoints attaches to nothing — Traefik builds it cleanly at
//     startup with no error, but every request against it gets
//     Traefik's own "no matching router" 404, which is easy to
//     mistake for a stripPrefix or backend problem since the 404 body
//     is byte-identical to Go's own default "404 page not found". The
//     entrypoint name itself comes from config.Config.TraefikEntryPoint
//     rather than being hardcoded — see its doc comment for why it
//     needs to vary by deployment.
//  2. The backend URL's host must resolve to wherever antiloop is
//     actually reachable from Traefik's own network namespace.
//     "127.0.0.1" only works when Traefik shares antiloop's namespace
//     (bare-metal or host-networked Traefik); in a bridge-networked
//     Docker container, "127.0.0.1" is the container's own loopback,
//     giving a clean 502 once routing itself is otherwise correct. See
//     TraefikBackendHost's doc comment.
//
// The TLS block ("tls: {}") is conditional on config.Config.TraefikTLS
// rather than always emitted — false (the default) matches a topology
// where TLS termination happens once, centrally, at a separate edge
// Traefik instance that fronts multiple hosts and forwards to each of
// them over plain HTTP; true restores TLS termination at this host's
// own Traefik for a deployment with no edge proxy in front. See
// TraefikTLS's doc comment.
//
// %[5]s is the tls block (including its own trailing newline) when
// TraefikTLS is true, or an empty string when false — see Register's
// tlsEnabled param.
const dynamicConfigTemplate = `# Generated by antiloop at startup — DO NOT EDIT BY HAND.
# Removed automatically on graceful shutdown; if antiloop crashed
# instead of shutting down cleanly, a stale file here means Traefik
# will keep routing to a port nothing is listening on anymore until
# this file is deleted (or antiloop is restarted, which overwrites it).
http:
  routers:
    %[1]s:
      rule: "PathPrefix(` + "`" + `/%[1]s` + "`" + `)"
      service: %[1]s
      entryPoints:
        - %[3]s
%[5]s      middlewares:
        - %[1]s-stripprefix
  middlewares:
    %[1]s-stripprefix:
      stripPrefix:
        prefixes:
          - "/%[1]s"
  services:
    %[1]s:
      loadBalancer:
        servers:
          - url: "http://%[4]s:%[2]d"
`

// tlsBlock returns the "tls: {}" line (with trailing newline, already
// indented to match the router block) when enabled, or "" when not —
// splices into dynamicConfigTemplate's %[5]s.
func tlsBlock(enabled bool) string {
	if !enabled {
		return ""
	}
	return "      tls: {}\n"
}

// configPath is the one place the <centre_id>.yml filename convention
// is decided — Register and Deregister must agree on it (Deregister
// doesn't get the port, only the centre_id, so it re-derives the same
// path rather than being told it).
func configPath(dynamicDir, centreID string) string {
	return filepath.Join(dynamicDir, centreID+".yml")
}

// Register writes this centre's Traefik dynamic-config file, pointing
// at the given port on backendHost — call once at startup, after the
// metrics listener is already bound and its actual port is known
// (e.g. via net.Listener.Addr(), since METRICS_ADDR defaults to :0 —
// see config.Config's MetricsAddr doc comment). entryPoint, backendHost
// and tlsEnabled come straight from config.Config's TraefikEntryPoint /
// TraefikBackendHost / TraefikTLS — see their doc comments for why all
// three need to be configurable rather than hardcoded (entrypoint
// naming, host-vs-container networking, and now TLS-vs-plain all vary
// by how Traefik itself is deployed, which this package has no way to
// know on its own).
//
// dynamicDir must already exist and already be watched by Traefik's
// own static file-provider config — this package only ever writes one
// file into it, it doesn't touch Traefik's own configuration.
func Register(dynamicDir, centreID string, port int, entryPoint, backendHost string, tlsEnabled bool) error {
	content := fmt.Sprintf(dynamicConfigTemplate, centreID, port, entryPoint, backendHost, tlsBlock(tlsEnabled))
	path := configPath(dynamicDir, centreID)
	// 0644: Traefik just needs to read it — no reason to restrict
	// further, and an overly-restrictive mode risks Traefik (running
	// as its own user) failing to read a file antiloop just wrote.
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		return fmt.Errorf("traefik: writing dynamic config %s: %w", path, err)
	}
	return nil
}

// Deregister removes this centre's dynamic-config file — call on
// graceful shutdown so Traefik stops routing to a port that's about to
// stop listening. Best-effort: a missing file (already removed, or
// dynamicDir doesn't exist) is not an error worth failing shutdown
// over.
func Deregister(dynamicDir, centreID string) error {
	path := configPath(dynamicDir, centreID)
	if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("traefik: removing dynamic config %s: %w", path, err)
	}
	return nil
}
